-- MySQL Script generated by MySQL Workbench
-- Thu Oct  9 11:11:20 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`TB_CacaPalavras`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`TB_CacaPalavras` (
  `PK_CacaPalavrasID` INT NOT NULL,
  PRIMARY KEY (`PK_CacaPalavrasID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TB_RespostaCerta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`TB_RespostaCerta` (
  `PK_RespostaCertaID` INT NOT NULL,
  `RespostaCerta` VARCHAR(45) NOT NULL,
  `TB_CacaPalavras_PK_CacaPalavrasID` INT NOT NULL,
  PRIMARY KEY (`PK_RespostaCertaID`, `TB_CacaPalavras_PK_CacaPalavrasID`),
  INDEX `fk_TB_RespostaCerta_TB_CacaPalavras_idx` (`TB_CacaPalavras_PK_CacaPalavrasID` ASC) VISIBLE,
  CONSTRAINT `fk_TB_RespostaCerta_TB_CacaPalavras`
    FOREIGN KEY (`TB_CacaPalavras_PK_CacaPalavrasID`)
    REFERENCES `mydb`.`TB_CacaPalavras` (`PK_CacaPalavrasID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
