-- MySQL Script generated by MySQL Workbench
-- Thu Oct  9 08:34:29 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`TB_cacaPalavras`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`TB_cacaPalavras` (
  `idTB_cacaPalavras` INT NOT NULL,
  `nomeCacaPalavras` VARCHAR(255) NULL,
  PRIMARY KEY (`idTB_cacaPalavras`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TB_respostaCerta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`TB_respostaCerta` (
  `idTB_respostaCerta` INT NOT NULL,
  `palavra` VARCHAR(255) NULL,
  `TB_cacaPalavras_idTB_cacaPalavras` INT NOT NULL,
  PRIMARY KEY (`idTB_respostaCerta`, `TB_cacaPalavras_idTB_cacaPalavras`),
  INDEX `fk_TB_respostaCerta_TB_cacaPalavras_idx` (`TB_cacaPalavras_idTB_cacaPalavras` ASC) VISIBLE,
  CONSTRAINT `fk_TB_respostaCerta_TB_cacaPalavras`
    FOREIGN KEY (`TB_cacaPalavras_idTB_cacaPalavras`)
    REFERENCES `mydb`.`TB_cacaPalavras` (`idTB_cacaPalavras`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
