-- MySQL Script generated by MySQL Workbench
-- Thu Oct  9 08:37:43 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`TB_CacaPalavras`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`TB_CacaPalavras` (
  `idTB_caca_palavras` INT NOT NULL,
  `nome_caca_palavras` VARCHAR(50) NULL,
  PRIMARY KEY (`idTB_caca_palavras`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TB_RespostaCerta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`TB_RespostaCerta` (
  `idTB_resposta_certa` INT NOT NULL,
  `palavra` VARCHAR(50) NULL,
  `TB_caca_palavras_idTB_caca_palavras` INT NOT NULL,
  PRIMARY KEY (`idTB_resposta_certa`, `TB_caca_palavras_idTB_caca_palavras`),
  INDEX `fk_TB_respostaCerta_TB_cacaPalavras_idx` (`TB_caca_palavras_idTB_caca_palavras` ASC) VISIBLE,
  CONSTRAINT `fk_TB_respostaCerta_TB_cacaPalavras`
    FOREIGN KEY (`TB_caca_palavras_idTB_caca_palavras`)
    REFERENCES `mydb`.`TB_CacaPalavras` (`idTB_caca_palavras`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
