-- MySQL Script generated by MySQL Workbench
-- Thu Sep 11 17:37:02 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema sprint_01
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sprint_01
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sprint_01` DEFAULT CHARACTER SET utf8 ;
USE `sprint_01` ;

-- -----------------------------------------------------
-- Table `sprint_01`.`Aluno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sprint_01`.`Aluno` (
  `apelido` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  `pontuacao` INT UNSIGNED NOT NULL DEFAULT 0,
  PRIMARY KEY (`apelido`),
  UNIQUE INDEX `apelido_UNIQUE` (`apelido` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sprint_01`.`ProgressoAluno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sprint_01`.`ProgressoAluno` (
  `idProgressoAluno` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `aluno_apelido` VARCHAR(45) NOT NULL,
  `Aluno_apelido` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idProgressoAluno`),
  INDEX `fk_ProgressoAluno_Aluno_idx` (`Aluno_apelido` ASC) VISIBLE,
  CONSTRAINT `fk_ProgressoAluno_Aluno`
    FOREIGN KEY (`Aluno_apelido`)
    REFERENCES `sprint_01`.`Aluno` (`apelido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
