-- MySQL Script generated by MySQL Workbench
-- Thu Sep 18 01:53:45 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Ilha`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Ilha` (
  `idIlha` INT NOT NULL,
  `nomeIlha` VARCHAR(45) NULL,
  `estadoIlha` TINYINT NULL,
  `foiJogada` TINYINT NULL,
  `enumNomeIlha` VARCHAR(45) NULL,
  PRIMARY KEY (`idIlha`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Desafio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Desafio` (
  `idDesafio` INT NOT NULL,
  `Ilha_idIlha` INT NOT NULL,
  PRIMARY KEY (`idDesafio`),
  INDEX `fk_Desafio_Ilha_idx` (`Ilha_idIlha` ASC) VISIBLE,
  CONSTRAINT `fk_Desafio_Ilha`
    FOREIGN KEY (`Ilha_idIlha`)
    REFERENCES `mydb`.`Ilha` (`idIlha`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Progresso Aluno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Progresso Aluno` (
  `idProgresso Aluno` INT NOT NULL,
  `Pontuação total` INT NULL,
  PRIMARY KEY (`idProgresso Aluno`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Progresso_Aluno has Ilha`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Progresso_Aluno has Ilha` (
  `Progresso Aluno_idProgresso Aluno` INT NOT NULL,
  `Ilha_idIlha` INT NOT NULL,
  INDEX `fk_Progresso_Aluno has Ilha_Progresso Aluno1_idx` (`Progresso Aluno_idProgresso Aluno` ASC) VISIBLE,
  INDEX `fk_Progresso_Aluno has Ilha_Ilha1_idx` (`Ilha_idIlha` ASC) VISIBLE,
  CONSTRAINT `fk_Progresso_Aluno has Ilha_Progresso Aluno1`
    FOREIGN KEY (`Progresso Aluno_idProgresso Aluno`)
    REFERENCES `mydb`.`Progresso Aluno` (`idProgresso Aluno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Progresso_Aluno has Ilha_Ilha1`
    FOREIGN KEY (`Ilha_idIlha`)
    REFERENCES `mydb`.`Ilha` (`idIlha`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
