-- MySQL Script generated by MySQL Workbench
-- Thu Sep 18 11:10:55 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Ilha`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Ilha` (
  `idIlha` INT NOT NULL AUTO_INCREMENT,
  `nomeIlha` ENUM('Dadolandia', 'Ciencias', 'Geografia', 'Matematica', 'Historia') NOT NULL,
  `estadoIlha` TINYINT(1) NOT NULL,
  `foiJogada` TINYINT(1) NOT NULL,
  PRIMARY KEY (`idIlha`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Aluno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Aluno` (
  `apelido` VARCHAR(50) NOT NULL,
  `senha` VARCHAR(50) NULL,
  `pontuacao` INT NULL,
  `progresso` VARCHAR(45) NULL,
  `ProgressoAluno_idAluno` INT NOT NULL,
  PRIMARY KEY (`apelido`),
  UNIQUE INDEX `apelido_UNIQUE` (`apelido` ASC) VISIBLE,
  INDEX `fk_Aluno_ProgressoAluno1_idx` (`ProgressoAluno_idAluno` ASC) VISIBLE,
  CONSTRAINT `fk_Aluno_ProgressoAluno1`
    FOREIGN KEY (`ProgressoAluno_idAluno`)
    REFERENCES `mydb`.`ProgressoAluno` (`idAluno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ProgressoAluno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ProgressoAluno` (
  `idAluno` INT NOT NULL,
  `pontuacaoTotalAluno` INT NULL,
  `apelido_aluno` VARCHAR(45) NULL,
  PRIMARY KEY (`idAluno`),
  INDEX `apelido_aluno_idx` (`apelido_aluno` ASC) VISIBLE,
  CONSTRAINT `apelido_aluno`
    FOREIGN KEY (`apelido_aluno`)
    REFERENCES `mydb`.`Aluno` (`apelido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Desafio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Desafio` (
  `idDesafio` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`idDesafio`),
  CONSTRAINT `idIlhaD`
    FOREIGN KEY (`idDesafio`)
    REFERENCES `mydb`.`Ilha` (`idIlha`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ProgressoAluno_has_Ilha`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ProgressoAluno_has_Ilha` (
  `ProgressoAluno_idAluno` INT NOT NULL,
  `Ilha_idIlha` INT NOT NULL,
  PRIMARY KEY (`ProgressoAluno_idAluno`, `Ilha_idIlha`),
  INDEX `fk_ProgressoAluno_has_Ilha_Ilha1_idx` (`Ilha_idIlha` ASC) VISIBLE,
  INDEX `fk_ProgressoAluno_has_Ilha_ProgressoAluno1_idx` (`ProgressoAluno_idAluno` ASC) VISIBLE,
  CONSTRAINT `fk_ProgressoAluno_has_Ilha_ProgressoAluno1`
    FOREIGN KEY (`ProgressoAluno_idAluno`)
    REFERENCES `mydb`.`ProgressoAluno` (`idAluno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ProgressoAluno_has_Ilha_Ilha1`
    FOREIGN KEY (`Ilha_idIlha`)
    REFERENCES `mydb`.`Ilha` (`idIlha`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
