-- MySQL Script generated by MySQL Workbench
-- Thu Oct 23 06:21:12 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`TB_TiposDesafios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`TB_TiposDesafios` (
  `PK_TiposDesafiosID` INT NOT NULL,
  `tipoDesafio` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`PK_TiposDesafiosID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TB_Desafio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`TB_Desafio` (
  `PK_DesafioID` INT NOT NULL,
  `TB_TiposDesafios_PK_TiposDesafiosID` INT NOT NULL,
  `pontuacaoDesafio` INT NULL,
  `isConcluido` TINYINT NOT NULL,
  PRIMARY KEY (`PK_DesafioID`, `TB_TiposDesafios_PK_TiposDesafiosID`),
  INDEX `fk_TB_Desafio_TB_TiposDesafios_idx` (`TB_TiposDesafios_PK_TiposDesafiosID` ASC) VISIBLE,
  CONSTRAINT `fk_TB_Desafio_TB_TiposDesafios`
    FOREIGN KEY (`TB_TiposDesafios_PK_TiposDesafiosID`)
    REFERENCES `mydb`.`TB_TiposDesafios` (`PK_TiposDesafiosID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
