-- MySQL Script generated by MySQL Workbench
-- Thu Oct 23 07:16:57 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`TB_Ilha`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`TB_Ilha` (
  `PK_IdIlha` INT NOT NULL AUTO_INCREMENT,
  `nomeIlha` VARCHAR(255) NOT NULL,
  `estadoIlha` TINYINT NULL,
  `foiJogada` TINYINT NULL,
  PRIMARY KEY (`PK_IdIlha`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TB_Desafio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`TB_Desafio` (
  `PK_Desafio` INT NOT NULL AUTO_INCREMENT,
  `tipoDesafio` VARCHAR(255) NULL,
  `pontuacaoDesafio` INT NULL,
  `isConcluido` TINYINT NULL,
  `TB_Ilha_PK_IdIlha` INT NOT NULL,
  PRIMARY KEY (`PK_Desafio`),
  INDEX `fk_TB_Desafio_TB_Ilha_idx` (`TB_Ilha_PK_IdIlha` ASC) VISIBLE,
  CONSTRAINT `fk_TB_Desafio_TB_Ilha`
    FOREIGN KEY (`TB_Ilha_PK_IdIlha`)
    REFERENCES `mydb`.`TB_Ilha` (`PK_IdIlha`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
